<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Testing" name="com.negativos.mandatorios.TCCamposMandatoriosContactos" tests="2" failures="1" timestamp="1 Oct 2015 22:12:43 GMT" time="27.544" errors="0">
  <testcase name="camposMandatoriosContactos" time="15.072" classname="com.negativos.mandatorios.TCCamposMandatoriosContactos">
    <failure type="java.lang.AssertionError" message="expected:&lt;&gt; but was:&lt;Protección - Login&gt;">
      <![CDATA[java.lang.AssertionError: expected:<> but was:<Protección - Login>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at com.negativos.mandatorios.TCCamposMandatoriosContactos.camposMandatoriosContactos(TCCamposMandatoriosContactos.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- camposMandatoriosContactos -->
  <testcase name="camposMandatoriosContactos" time="12.472" classname="com.negativos.mandatorios.TCCamposMandatoriosContactos"/>
</testsuite> <!-- com.negativos.mandatorios.TCCamposMandatoriosContactos -->
